server.port=${PORT:8080}

spring.application.name=anoulam-backend

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

app.security.token=${ANOULAM_TOKEN_KEY}